# Generated by Django 4.0.2 on 2022-03-02 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='area',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance',
            field=models.IntegerField(default=0, editable=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(max_length=400, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='discord',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
